model:
  mm_vision_tower: "google/siglip-base-patch16-224"
  mm_audio_tower: "openai/whisper-large-v3"
  model_size: "0.5B"

data:
  label_path: "/mnt/ssd_hs/Dataset/DFEW/label/single_testset_5.csv"
  video_dataset_name: "DFEW"

