model:
  mm_vision_tower: "google/siglip-so400m-patch14-384"
  mm_audio_tower: "openai/whisper-large-v3"
  model_size: "7B"

data:
  label_path: "/mnt/ssd_hs/Dataset/DFEW/label/single_testset_5.csv"
  video_dataset_name: "DFEW"
