modal: "video_audio"

model:
  mm_vision_tower: /mnt/ssd_hs/Exp/R1-Omni/pre-trained/siglip-base-patch16-224
  mm_audio_tower: /mnt/ssd_hs/Exp/R1-Omni/pre-trained/whisper-large-v3
  model_size: "0.5B"

data:
  # model_path: "/mnt/ssd_hs/Exp/R1-Omni/src/r1-v/results-0416-sft-rlvr/checkpoint-2088"
  # model_path: "/mnt/ssd_hs/Exp/R1-Omni/src/r1-v/results-0420-sft-rlvr-add-gpt"
  
  # model_path: "/mnt/ssd_hs/Exp/R1-Omni/work_dirs/humanomniqwen2_siglip/finetune_EMER_SFT"
  # model_path: "StarJiaxing/R1-Omni-0.5B"
  # model_path: "StarJiaxing/HumanOmni-0.5B"
  model_path: "/mnt/ssd_hs/Exp/R1-Omni/src/r1-v/results-0426-sft-rlvr-no-emotion"
  label_path: "/mnt/ssd_hs/Dataset/DFEW/label/single_testset_5.csv"
  video_dataset_name: "DFEW"



# output_path:  "./results/DFEW/my-rethink-R1-Omni-0.5B/output_eval5-av.txt"

# instruct: "As an emotional recognition expert; throughout the video, which emotion conveyed by the characters is the most obvious to you? Output the thinking process in <think> </think> and final emotion in <answer> </answer> tags."

# instruct: "As an emotional recognition expert; throughout the video, which emotion conveyed by the characters is the most obvious to you?\n happy ,surprise ,neutral ,angry ,disgust ,sad ,fear. Output the thinking process in <think> </think> and final emotion in <answer> </answer> tags."
CUDA_VISIBLE_DEVICES: 1
