modal: "audio"

model:
  mm_vision_tower: "/mnt/ssd_hs/Exp/R1-Omni/pre-trained/siglip-so400m-patch14-384"
  mm_audio_tower: /mnt/ssd_hs/Exp/R1-Omni/pre-trained/whisper-large-v3
  model_size: "7B"

data:
  model_path: "/mnt/ssd_hs/Exp/R1-Omni/pre-trained/HumanOmni-7B"
  label_path: "/mnt/ssd_hs/Exp/R1-Omni/configs/data_files/EMER/final-EMER-reason.csv"
  video_dataset_name: "EMER"


CUDA_VISIBLE_DEVICES: 5
