model:
  mm_vision_tower: "google/siglip-so400m-patch14-384"
  mm_audio_tower: "openai/whisper-large-v3"
  model_size: "7B"

data:
  video_dataset_name: "MAFW"
  label_path: "/mnt/ssd_hs/Dataset/MAFW/Train & Test Set/single/no_caption/set_5/test.txt"

