modal: "video_audio"

model:
  mm_vision_tower: /mnt/ssd_hs/Exp/R1-Omni/pre-trained/siglip-base-patch16-224
  mm_audio_tower: /mnt/ssd_hs/Exp/R1-Omni/pre-trained/whisper-large-v3

data:
  model_path: "StarJiaxing/R1-Omni-0.5B"
  # model_path: "StarJiaxing/EMER-SFT-0.5B"
  # model_path: "StarJiaxing/HumanOmni-7B" 
  # label_path: "/mnt/ssd_hs/Dataset/DFEW/label/single_testset_5.csv"
  video_dataset_name: "MAFW"
  label_path: "/mnt/ssd_hs/Dataset/MAFW/Train & Test Set/single/no_caption/set_5/test.txt"


output_path:  "./results/MAFW/output_eval5_R1-Omni-0.5B-emotion_label_ref.txt"
# instruct: "As an emotional recognition expert; throughout the video, which emotion conveyed by the characters is the most obvious to you?  Output the thinking process in <think> </think> and final emotion in <answer> </answer> tags."
# instruct: "As an emotional recognition expert; throughout the video, which emotion conveyed by the characters is the most obvious to you?\nfear ,angry ,surprise ,happy ,neutral ,sad ,disgust"
instruct: "As an emotional recognition expert; throughout the video, which emotion conveyed by the characters is the most obvious to you?\nanger ,disgust ,fear ,happiness ,neutral ,sadness ,surprise, contempt, anxiety, helplessness, disappointment. Output the thinking process in <think> </think> and final emotion in <answer> </answer> tags."
CUDA_VISIBLE_DEVICES: 1
